=== sahil-tandon/IS7024-BandIt/BandIt/BandIt/uservalidation.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">   
   <xs:element name="userdetails"> 
          <xs:complexType>       
             <xs:sequence>             
                <xs:element name="users" maxOccurs="unbounded">
                  <xs:complexType>       
                     <xs:sequence>             
                        <xs:element name="firstname" type="xs:string"/>         
                        <xs:element name="lastname"  type="xs:string"/> 
                        <xs:element name="bearcatid"  type="xs:string"/> 
                        <xs:element name="favoriteshortcut"  type="xs:string"/> 
                     </xs:sequence>     
                  </xs:complexType>   
                </xs:element>
             </xs:sequence>
          </xs:complexType> 
   </xs:element>  
</xs:schema>

=== sahil-tandon/IS7024-BandIt/BandIt/BandIt/teamdetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<userdetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uservalidation.xsd">
   <users>
      <firstname>Sahil</firstname>
      <lastname>Tandon</lastname>
      <bearcatid>M12948683</bearcatid>
      <favoriteshortcut>Ctrl + F5</favoriteshortcut>
   </users>
   <users>
      <firstname>Hasnain</firstname>
      <lastname>Kurawadwala</lastname>
      <bearcatid>M12948309</bearcatid>
      <favoriteshortcut>Windows + K</favoriteshortcut>
   </users>
   <users>
      <firstname>Sidhartha</firstname>
      <lastname>Bora</lastname>
      <bearcatid>M12948050</bearcatid>
      <favoriteshortcut>Ctrl + Z</favoriteshortcut>
   </users>
   <users>
      <firstname>Sudhakar</firstname>
      <lastname>Samak</lastname>
      <bearcatid>M12825376</bearcatid>
      <favoriteshortcut>Ctrl + Shift + Del</favoriteshortcut>
   </users>
</userdetails>
